apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "etlaksKeyVault"
    objects: |
      array:
        - objectName: "APIKEY"
          objectType: secret
    tenantId: ""
